apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dmudrakola/devops-projects.git
    targetRevision: HEAD
    path: overlays/prod # ArgoCD will only look in this folder for the manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default # The namespace where the app will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
